### ISSUE TITLE
Update to Confluent.Kafka 1.8.2 produces error - Expected 48 bytes but read 17 bytes

### ISSUE THREAD

**Issue by ciezekiel** [Fresa/Kafka.Protocol#1]
On a test project with Kafka.TestFramework i am getting the following error:
System.InvalidOperationException : Expected 48 bytes but read 17 bytes
from Kafka.Protocol.

The way to reproduce is to update the version from Kafka.TestFamework to latest Confluent.Kafka (1.8.2).
Latest version without error is 1.3.0

**Comment by Fresa** [comment]
The exception is hiding the real issue, which should be fixed at some point.

The real problem is that the Confluent.Kafka client is sending an unsupported ApiVersionRequest. Supported versions by Kafka.Protocol are currently 0-2, the client sends 3. 

Not really sure how that scenario is supposed to be handled. Tried responding with the version 2 and an UNSUPPORTED_VERSION error code which rdkafka seems to be able to interpret but it will panic and not continue the negotiation process.

Anyway, the protocol definition in Kafka.Protocol should probably be upgraded at some point. If you want to give it a go your more than welcome with a PR :)

**Comment by Fresa** [comment]
@ciezekiel I just released a new v2.0.0 version which supports the Confluent.Kafka 1.8.2 version, https://github.com/Fresa/Kafka.Protocol/releases/tag/v2.0.0. 

Kafka.TestFramework has been updated accordingly, https://github.com/Fresa/Kafka.TestFramework/releases/tag/v2.0.0

The protocol has been tested with both Confluent.Kafka 1.8.2 as with the older previously tested version of 1.1.0 and works with both and presumable with all versions in between.

I'll close this ticket.
